name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create quizmaster database
        run: psql -U postgres -h localhost -f backend/create_db.sql
        env:
          PGPASSWORD: postgres

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Run backend tests
        working-directory: backend
        run: ./gradlew test

      - name: Run end-to-end tests
        working-directory: backend
        run: ./gradlew testE2E

      - name: Lint frontend
        working-directory: frontend
        run: pnpm biome lint

      - name: Format frontend
        working-directory: frontend
        run: pnpm biome format --check
